### ISSUE TITLE
Changes to kexp.org/playlist break scraping logic.

### ISSUE THREAD

**Issue by 28mm** [28mm/KEX.Py#2]
Changes to http://kexp.org/playlist/ have broken the playlist scraping logic in KEX.Py. A simple solution is to use the same source of json playlists that the website uses.

**Comment by pmthomps** [comment]
See Pull Request https://github.com/28mm/KEX.Py/pull/4 for fix that removes dependency on kexp.org/playlist and instead uses the KEXP REST API.
